version: "3.4"

services:
  controller:
    image: ghcr.io/unicornunicode/fact-controller:main
    command:
      - --listen-addr
      - 0.0.0.0:5123
      - --elasticsearch-host
      - http://elasticsearch:9200
    networks:
      - fact
    volumes:
      - controller-database:/var/lib/fact
  worker:
    image: ghcr.io/unicornunicode/fact-worker:main
    restart: always
    command:
      - --controller-addr
      - controller:5123
    networks:
      - fact
    volumes:
      - worker-data:/var/lib/fact
    privileged: true
  grpcwebproxy:
    image: ghcr.io/unicornunicode/fact-grpcwebproxy:main
    command:
      - --backend_addr=controller:5123
      - --server_http_debug_port=5124
    networks:
      - fact
    ports:
      - 5124:5124
  ui:
    image: ghcr.io/unicornunicode/fact-ui:main
    environment:
      # Update to match the host IP address. This must be a valid, routed address
      # accessible throughout the Docker network and on your host.
      # You can get your host IP address by looking up your system's network
      # information.
      - MANAGEMENT_ENDPOINT=http://HOST_IP:5124
    networks:
      - fact
    ports:
      - 3000:3000
    # Alternatively, if you wish to experiment locally, you can make this
    # container use host networking by commenting out the `environment`,
    # `networks` and `ports` sections above and set MANAGEMENT_ENDPOINT
    # accordingly:
    #environment:
    #  - MANAGEMENT_ENDPOINT=http://localhost:5124
    #network_mode: host
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - fact
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - fact
    ports:
      - 5601:5601

networks:
  fact:

volumes:
  controller-database:
  worker-data:
  elasticsearch:
# vim: set et ts=2 sw=2:
