"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import fact.controller_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class CreateTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TASK_NONE_FIELD_NUMBER: builtins.int
    TASK_COLLECT_DISK_FIELD_NUMBER: builtins.int
    TASK_COLLECT_MEMORY_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    @property
    def task_none(self) -> fact.controller_pb2.TaskNone: ...
    @property
    def task_collect_disk(self) -> fact.controller_pb2.TaskCollectDisk: ...
    @property
    def task_collect_memory(self) -> fact.controller_pb2.TaskCollectMemory: ...
    target: builtins.bytes = ...
    def __init__(self,
        *,
        task_none : typing.Optional[fact.controller_pb2.TaskNone] = ...,
        task_collect_disk : typing.Optional[fact.controller_pb2.TaskCollectDisk] = ...,
        task_collect_memory : typing.Optional[fact.controller_pb2.TaskCollectMemory] = ...,
        target : builtins.bytes = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["task",b"task","task_collect_disk",b"task_collect_disk","task_collect_memory",b"task_collect_memory","task_none",b"task_none"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["target",b"target","task",b"task","task_collect_disk",b"task_collect_disk","task_collect_memory",b"task_collect_memory","task_none",b"task_none"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task",b"task"]) -> typing.Optional[typing_extensions.Literal["task_none","task_collect_disk","task_collect_memory"]]: ...
global___CreateTaskRequest = CreateTaskRequest

class TargetSelector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___TargetSelector = TargetSelector

class CreateTaskResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UUID_FIELD_NUMBER: builtins.int
    uuid: builtins.bytes = ...
    def __init__(self,
        *,
        uuid : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uuid",b"uuid"]) -> None: ...
global___CreateTaskResult = CreateTaskResult

class ListTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ListTaskRequest = ListTaskRequest

class ListTaskResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TASKS_FIELD_NUMBER: builtins.int
    @property
    def tasks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListTask]: ...
    def __init__(self,
        *,
        tasks : typing.Optional[typing.Iterable[global___ListTask]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tasks",b"tasks"]) -> None: ...
global___ListTaskResult = ListTaskResult

class ListTask(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Status(_Status, metaclass=_StatusEnumTypeWrapper):
        pass
    class _Status:
        V = typing.NewType('V', builtins.int)
    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        WAITING = ListTask.Status.V(0)
        RUNNING = ListTask.Status.V(1)
        COMPLETE = ListTask.Status.V(2)

    WAITING = ListTask.Status.V(0)
    RUNNING = ListTask.Status.V(1)
    COMPLETE = ListTask.Status.V(2)

    UUID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    ASSIGNED_AT_FIELD_NUMBER: builtins.int
    COMPLETED_AT_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    TASK_NONE_FIELD_NUMBER: builtins.int
    TASK_COLLECT_DISK_FIELD_NUMBER: builtins.int
    TASK_COLLECT_MEMORY_FIELD_NUMBER: builtins.int
    WORKER_FIELD_NUMBER: builtins.int
    uuid: builtins.bytes = ...
    status: global___ListTask.Status.V = ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def assigned_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def completed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    target: builtins.bytes = ...
    """Target UUID"""

    @property
    def task_none(self) -> fact.controller_pb2.TaskNone: ...
    @property
    def task_collect_disk(self) -> fact.controller_pb2.TaskCollectDisk: ...
    @property
    def task_collect_memory(self) -> fact.controller_pb2.TaskCollectMemory: ...
    worker: builtins.bytes = ...
    """Worker UUID"""

    def __init__(self,
        *,
        uuid : builtins.bytes = ...,
        status : global___ListTask.Status.V = ...,
        created_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        assigned_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        completed_at : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        target : builtins.bytes = ...,
        task_none : typing.Optional[fact.controller_pb2.TaskNone] = ...,
        task_collect_disk : typing.Optional[fact.controller_pb2.TaskCollectDisk] = ...,
        task_collect_memory : typing.Optional[fact.controller_pb2.TaskCollectMemory] = ...,
        worker : builtins.bytes = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["assigned_at",b"assigned_at","completed_at",b"completed_at","created_at",b"created_at","task",b"task","task_collect_disk",b"task_collect_disk","task_collect_memory",b"task_collect_memory","task_none",b"task_none"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["assigned_at",b"assigned_at","completed_at",b"completed_at","created_at",b"created_at","status",b"status","target",b"target","task",b"task","task_collect_disk",b"task_collect_disk","task_collect_memory",b"task_collect_memory","task_none",b"task_none","uuid",b"uuid","worker",b"worker"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task",b"task"]) -> typing.Optional[typing_extensions.Literal["task_none","task_collect_disk","task_collect_memory"]]: ...
global___ListTask = ListTask

class ListWorkerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___ListWorkerRequest = ListWorkerRequest

class ListWorkerResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UUID_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    uuid: builtins.bytes = ...
    hostname: typing.Text = ...
    def __init__(self,
        *,
        uuid : builtins.bytes = ...,
        hostname : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hostname",b"hostname","uuid",b"uuid"]) -> None: ...
global___ListWorkerResult = ListWorkerResult
