# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fact/tasks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fact/tasks.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x66\x61\x63t/tasks.proto\";\n\x06Target\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x19\n\x03ssh\x18\x02 \x01(\x0b\x32\n.SSHAccessH\x00\x42\x08\n\x06\x61\x63\x63\x65ss\"s\n\tSSHAccess\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x13\n\x0bprivate_key\x18\x04 \x01(\t\x12\x0e\n\x06\x62\x65\x63ome\x18\x05 \x01(\x08\x12\x17\n\x0f\x62\x65\x63ome_password\x18\x06 \x01(\t\"\n\n\x08TaskNone\"\x10\n\x0eTaskNoneResult\"9\n\x0fTaskCollectDisk\x12&\n\x08selector\x18\x02 \x01(\x0b\x32\x14.CollectDiskSelector\"\x17\n\x15TaskCollectDiskResult\"#\n\x13\x43ollectDiskSelector\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x13\n\x11TaskCollectMemory\"\x19\n\x17TaskCollectMemoryResult\"\x12\n\x10TaskCollectLsblk\"R\n\x0bLsblkResult\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x12\n\nmountpoint\x18\x04 \x01(\t\"=\n\x16TaskCollectLsblkResult\x12#\n\rlsblk_results\x18\x01 \x03(\x0b\x32\x0c.LsblkResultb\x06proto3'
)




_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='Target.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ssh', full_name='Target.ssh', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='access', full_name='Target.access',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=20,
  serialized_end=79,
)


_SSHACCESS = _descriptor.Descriptor(
  name='SSHAccess',
  full_name='SSHAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='SSHAccess.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='SSHAccess.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='SSHAccess.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='private_key', full_name='SSHAccess.private_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='become', full_name='SSHAccess.become', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='become_password', full_name='SSHAccess.become_password', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=196,
)


_TASKNONE = _descriptor.Descriptor(
  name='TaskNone',
  full_name='TaskNone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=208,
)


_TASKNONERESULT = _descriptor.Descriptor(
  name='TaskNoneResult',
  full_name='TaskNoneResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=226,
)


_TASKCOLLECTDISK = _descriptor.Descriptor(
  name='TaskCollectDisk',
  full_name='TaskCollectDisk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='selector', full_name='TaskCollectDisk.selector', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=285,
)


_TASKCOLLECTDISKRESULT = _descriptor.Descriptor(
  name='TaskCollectDiskResult',
  full_name='TaskCollectDiskResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=310,
)


_COLLECTDISKSELECTOR = _descriptor.Descriptor(
  name='CollectDiskSelector',
  full_name='CollectDiskSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='CollectDiskSelector.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=347,
)


_TASKCOLLECTMEMORY = _descriptor.Descriptor(
  name='TaskCollectMemory',
  full_name='TaskCollectMemory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=368,
)


_TASKCOLLECTMEMORYRESULT = _descriptor.Descriptor(
  name='TaskCollectMemoryResult',
  full_name='TaskCollectMemoryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=395,
)


_TASKCOLLECTLSBLK = _descriptor.Descriptor(
  name='TaskCollectLsblk',
  full_name='TaskCollectLsblk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=415,
)


_LSBLKRESULT = _descriptor.Descriptor(
  name='LsblkResult',
  full_name='LsblkResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='LsblkResult.device_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='LsblkResult.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='LsblkResult.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mountpoint', full_name='LsblkResult.mountpoint', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=499,
)


_TASKCOLLECTLSBLKRESULT = _descriptor.Descriptor(
  name='TaskCollectLsblkResult',
  full_name='TaskCollectLsblkResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lsblk_results', full_name='TaskCollectLsblkResult.lsblk_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=562,
)

_TARGET.fields_by_name['ssh'].message_type = _SSHACCESS
_TARGET.oneofs_by_name['access'].fields.append(
  _TARGET.fields_by_name['ssh'])
_TARGET.fields_by_name['ssh'].containing_oneof = _TARGET.oneofs_by_name['access']
_TASKCOLLECTDISK.fields_by_name['selector'].message_type = _COLLECTDISKSELECTOR
_TASKCOLLECTLSBLKRESULT.fields_by_name['lsblk_results'].message_type = _LSBLKRESULT
DESCRIPTOR.message_types_by_name['Target'] = _TARGET
DESCRIPTOR.message_types_by_name['SSHAccess'] = _SSHACCESS
DESCRIPTOR.message_types_by_name['TaskNone'] = _TASKNONE
DESCRIPTOR.message_types_by_name['TaskNoneResult'] = _TASKNONERESULT
DESCRIPTOR.message_types_by_name['TaskCollectDisk'] = _TASKCOLLECTDISK
DESCRIPTOR.message_types_by_name['TaskCollectDiskResult'] = _TASKCOLLECTDISKRESULT
DESCRIPTOR.message_types_by_name['CollectDiskSelector'] = _COLLECTDISKSELECTOR
DESCRIPTOR.message_types_by_name['TaskCollectMemory'] = _TASKCOLLECTMEMORY
DESCRIPTOR.message_types_by_name['TaskCollectMemoryResult'] = _TASKCOLLECTMEMORYRESULT
DESCRIPTOR.message_types_by_name['TaskCollectLsblk'] = _TASKCOLLECTLSBLK
DESCRIPTOR.message_types_by_name['LsblkResult'] = _LSBLKRESULT
DESCRIPTOR.message_types_by_name['TaskCollectLsblkResult'] = _TASKCOLLECTLSBLKRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), {
  'DESCRIPTOR' : _TARGET,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:Target)
  })
_sym_db.RegisterMessage(Target)

SSHAccess = _reflection.GeneratedProtocolMessageType('SSHAccess', (_message.Message,), {
  'DESCRIPTOR' : _SSHACCESS,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:SSHAccess)
  })
_sym_db.RegisterMessage(SSHAccess)

TaskNone = _reflection.GeneratedProtocolMessageType('TaskNone', (_message.Message,), {
  'DESCRIPTOR' : _TASKNONE,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskNone)
  })
_sym_db.RegisterMessage(TaskNone)

TaskNoneResult = _reflection.GeneratedProtocolMessageType('TaskNoneResult', (_message.Message,), {
  'DESCRIPTOR' : _TASKNONERESULT,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskNoneResult)
  })
_sym_db.RegisterMessage(TaskNoneResult)

TaskCollectDisk = _reflection.GeneratedProtocolMessageType('TaskCollectDisk', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOLLECTDISK,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskCollectDisk)
  })
_sym_db.RegisterMessage(TaskCollectDisk)

TaskCollectDiskResult = _reflection.GeneratedProtocolMessageType('TaskCollectDiskResult', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOLLECTDISKRESULT,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskCollectDiskResult)
  })
_sym_db.RegisterMessage(TaskCollectDiskResult)

CollectDiskSelector = _reflection.GeneratedProtocolMessageType('CollectDiskSelector', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTDISKSELECTOR,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:CollectDiskSelector)
  })
_sym_db.RegisterMessage(CollectDiskSelector)

TaskCollectMemory = _reflection.GeneratedProtocolMessageType('TaskCollectMemory', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOLLECTMEMORY,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskCollectMemory)
  })
_sym_db.RegisterMessage(TaskCollectMemory)

TaskCollectMemoryResult = _reflection.GeneratedProtocolMessageType('TaskCollectMemoryResult', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOLLECTMEMORYRESULT,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskCollectMemoryResult)
  })
_sym_db.RegisterMessage(TaskCollectMemoryResult)

TaskCollectLsblk = _reflection.GeneratedProtocolMessageType('TaskCollectLsblk', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOLLECTLSBLK,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskCollectLsblk)
  })
_sym_db.RegisterMessage(TaskCollectLsblk)

LsblkResult = _reflection.GeneratedProtocolMessageType('LsblkResult', (_message.Message,), {
  'DESCRIPTOR' : _LSBLKRESULT,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:LsblkResult)
  })
_sym_db.RegisterMessage(LsblkResult)

TaskCollectLsblkResult = _reflection.GeneratedProtocolMessageType('TaskCollectLsblkResult', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOLLECTLSBLKRESULT,
  '__module__' : 'fact.tasks_pb2'
  # @@protoc_insertion_point(class_scope:TaskCollectLsblkResult)
  })
_sym_db.RegisterMessage(TaskCollectLsblkResult)


# @@protoc_insertion_point(module_scope)
