name: misc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "**.md"
      - "**.yml"
      - "**.yaml"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
          cache-dependency-path: .github/workflows/misc.yml
      - name: Install prettier
        run: npm install --no-save prettier@2
      - name: Format
        run: npx prettier --write '**/*.md' '**/*.yml' '**/*.yaml'
      - name: Commit changes if any
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m "style: Automatic code formatting" -a
            git push
          fi

# vim: set et ts=2 sw=2:
